repos:
  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        pass_filenames: false
        entry: poetry run black .
      - id: isort
        name: isort
        language: system
        pass_filenames: false
        entry: poetry run isort --profile black .
      - id: ruff
        name: ruff
        language: system
        pass_filenames: false
        entry: poetry run ruff . --line-length 120
      - id: pylint
        name: pylint
        language: system
        pass_filenames: false
        entry: poetry run pylint clusterfun --max-line-length 120
# do not run the following hooks on the frontend for now
# - id: prettier
#   name: prettier
#   language: system
#   pass_filenames: false
#   entry: npx prettier --write .
#      - id: eslint
#        name: eslint
#        language: system
#        pass_filenames: false
#        entry: npx eslint src/frontend
